mes_villes = ["Avignon","Clermont-Ferrand","Aix-en-Provence"]

# erreur : l'index 3 de cette liste n'existe pas
#print(mes_villes[3])
#Traceback (most recent call last):
# File "c:\Users\oliri\OneDrive\Documents\python\python_crash_course\3_introducing_lists\3-11-intentional error.py", line 2, in <module>
#    print(mes_villes[3])
#          ~~~~~~~~~~^^^
#IndexError: list index out of range

#Cette fois ci c'est OK

print(mes_villes[2])

